// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mosstroinform_mobile/core/database/adapters/construction_object_adapter.dart';
import 'package:mosstroinform_mobile/core/database/adapters/document_adapter.dart';
import 'package:mosstroinform_mobile/core/database/adapters/final_document_adapter.dart';
import 'package:mosstroinform_mobile/core/database/adapters/project_adapter.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ConstructionObjectAdapterAdapter());
    registerAdapter(ConstructionStageAdapterAdapter());
    registerAdapter(DocumentAdapterAdapter());
    registerAdapter(FinalDocumentAdapterAdapter());
    registerAdapter(ProjectAdapterAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ConstructionObjectAdapterAdapter());
    registerAdapter(ConstructionStageAdapterAdapter());
    registerAdapter(DocumentAdapterAdapter());
    registerAdapter(FinalDocumentAdapterAdapter());
    registerAdapter(ProjectAdapterAdapter());
  }
}
